sudo: required 
dist: trusty
language: node_js
node_js:
  - "6"
  - "7"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - google-chrome-stable
  firefox: "latest"
env:
  global:
    - DISPLAY=:99.0
    - CXX=g++-4.8
  matrix:
    - CXX=g++-4.8 TEST_SUITE=test:node
matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "6"
      env: CXX=g++-4.8 TEST_SUITE=coveralls
    - os: linux
      node_js: "6"
      env: CXX=g++-4.8 TEST_SUITE=lint
    - os: linux
      before_install:
        - sh -e /etc/init.d/xvfb start
      node_js: "6"
      env: CHROME_BIN=google-chrome CXX=g++-4.8 TEST_SUITE=test:browser
script: npm run $TEST_SUITE